/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include "fibonnaci_threads.h"
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>

struct thread_data{
   int thread_id;
   int fib_limit;
   int *winner;
};

struct thread_data thread_data_array[3];

// void fibonnaci (int fib, int thread_num, int *winner){
void *fibonnaci (void *targs) {

	struct thread_data *my_data;
  my_data = (struct thread_data *) targs;

	long long int c = 0, first = 0, second = 1, next = 0;

	for ( c = 0 ; c < 50 ; c++ )
   {
      if ( c <= 1 )
         next = c;
      else
      {
         next = first + second;
         first = second;
         second = next;
      }
      printf("%lld\n",next);
   }

	if( my_data->winner == 0){
		my_data->winner = (int *) my_data->thread_id;
	}
	printf("Thread %d finished and fib value is %lld and winner is %d ###########################################.\n", my_data->thread_id, next,(int) my_data->winner);

	pthread_exit(NULL);
}

int *
fib_1_svc(int *argp, struct svc_req *rqstp) {
	static int result;

	int *winner = 0;

	// thread t1(fibonacci, fib_limit, 1, winner);
	// thread t2(fibonacci, fib_limit, 2, winner);
	// thread t3(fibonacci, fib_limit, 3, winner);

	// t1.join();
	// t2.join();
	// t3.join();
	printf("Thread %d was chosen by user\n", argp[0]);

	pthread_t threads[3];

	int c;
	for (c = 0; c < 3; c++){
		thread_data_array[c].thread_id = c;
		thread_data_array[c].fib_limit = 5000;
		thread_data_array[c].winner = winner;
		pthread_create(&threads[c], NULL, fibonnaci, (void *) &thread_data_array[c]);

	}
	pthread_join(threads[0], NULL);
	pthread_join(threads[1], NULL);
	pthread_join(threads[2], NULL);

	printf("Thread %d won!\n", (int) winner);

	if (argp[0] ==  (int) winner) {
		result = 1;
	} else {
		result = 0;
	}

	return &result;
}
