/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIBONNACI_THREADS_H_RPCGEN
#define _FIBONNACI_THREADS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define fib_thread 0x3fffffff
#define fib_ver_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define FIB 1
extern  int * fib_1(int *, CLIENT *);
extern  int * fib_1_svc(int *, struct svc_req *);
extern int fib_thread_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FIB 1
extern  int * fib_1();
extern  int * fib_1_svc();
extern int fib_thread_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIBONNACI_THREADS_H_RPCGEN */
